# Generated by Django 5.1.2 on 2024-10-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_persona_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
